Alleyah Pauline C. Manalili

# <font color = red> ASSIGNMENT 1</font>

In [7]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

- The above python functions are developed to automate forward elimination.
- To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.

In [13]:
# Code for automating backward substitution
def backward_substitution(U):
    n = U.shape[0]
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        x[i] = U[i][-1] / U[i][i]
        for j in range(i - 1, -1, -1):
            U[j][-1] -= U[j][i] * x[i]
    
    return x

# More Examples
---
Solve the equation
$
\begin{equation}
x_1-x_2+x_3=3 \\
2x_1+x_2+8x_3 = 18 \\
4x_1+2x_2-3x_3 = -2 \\
\end{equation}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    2 & 1 & 8 &\bigm| & 18 \\
    4 & 2 & -3 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    4 & 2 & -3 &\bigm| & -2 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    4 & 2 & -3 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 4\text{R}_{1}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 6 & -7 &\bigm| & -14 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 6 & -7 &\bigm| & -14 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3}-2\text{R}_{2}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 3 & 6 &\bigm| & 12 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 1 & 2 &\bigm| & 4 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
$
<br><br>
$
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 1 & 2 &\bigm| & 4 \\
    0 & 0 & -19 &\bigm| & -38 \\
\end{pmatrix}
\xrightarrow{\frac{-1}{19}\text{R}_{3}}
\begin{pmatrix}
    1 & -1 & 1 &\bigm| & 3 \\
    0 & 1 & 2 &\bigm| & 4 \\
    0 & 0 & 1 &\bigm| & 2 \\
\end{pmatrix}
$
<br><br>
The system of equation has the solution:
$
\begin{equation}
x_1-x_2+x_3=3 \\
x_2+2x_3 = 4 \\
x_3 = 2 \\
\end{equation}
$
<br>
Performing back substitution yields:
$
\begin{equation}
x_1-x_2+x_3=3 \to x_1-0+2 = 3 \to x_1 = 3-2 = 1 \\
x_2+2x_3 = 4 \to x_2+2(2)=4 \to x_2+4=4 \to x_2 = 4-4 =0 \\
x_3 = 2 \\
\end{equation}
$
<br>
$\therefore \ x_1=1, x_2=0, x_3=2$

In [1]:
import numpy as np

# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

# Code for automating backward substitution
def backward_substitution(U):
    n = U.shape[0]
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        x[i] = U[i][-1] / U[i][i]
        for j in range(i - 1, -1, -1):
            U[j][-1] -= U[j][i] * x[i]
    
    return x

A=np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])

## Add -2 times row 0 to row 1
A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1,'\n')

## Add -4 times row 0 to row 2
A2 = RowAdd(A1,0,2,-4)
print("A2")
print(A2,'\n')

## Add -2 times row 1 to row 2
A3 = RowAdd(A2,1,2,-2)
print("A3")
print(A3,'\n')

## Multiply row 1 by 1/3
A4 = RowScale(A3,1,1.0/3)
print("A4")
print(A4,'\n')

## Multiply row 2 by 1/19
A5 = RowScale(A4,2,1.0/-19.)
print("A5")
print(A5,'\n')

## Backward Substitution
solution = backward_substitution(A5)
print("Solution:")
print(solution,'\n')

A1
[[ 1. -1.  1.  3.]
 [ 0.  3.  6. 12.]
 [ 4.  2. -3. -2.]] 

A2
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   6.  -7. -14.]] 

A3
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   0. -19. -38.]] 

A4
[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   0. -19. -38.]] 

A5
[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]] 

Solution:
[1. 0. 2.] 



# <font color = red> ASSIGNMENT 2</font>

1. Provide reasons why each of the following equations is, or is not, a linear equation.
- $\cos{\theta}x+4y+z = \sqrt{3}$ <br>
It is a linear equation because it follows $a_1x_1+a_2x_2+...+a_nx_n = b$.

- $cos{x}4y+z = \sqrt{3}$ <br>
It is not a linear equation because of the term  $cos{x}4y$.

- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$ <br>
It is not a linear equation. In linear equation, variables should be raised to the power of 1. However, in this case, $x^{-1}$ represents a non-linear term $1/x$.

- $x^1+y^1+z^1=0$ <br>
It is a linear equation because it follows $a_1x_1+a_2x_2+...+a_nx_n = b$ and all variables are raised to the power of 1, implying linearity.

2. Find the solutions to the linear equations:
- $2x_1+3x_2 =5$
<br><br>
Solving for $x_1$:
<br>
$2x_1 =5-3x_2$
<br>
$\frac{2x_1}{2} =\frac{5-3x_2}{2}$
<br>
$x_1 =\frac{5-3x_2}{2}$

In [18]:
import sympy as sp

x1, x2 = sp.symbols('x1 x2')
equation = sp.Eq(2*x1 + 3*x2, 5)
solution = sp.solve(equation, x1)

for sol in solution:
    print("x1 =", sol)

x1 = 5/2 - 3*x2/2


- $4x_1+3x_2+2x_3=1$
<br><br>
Solving for $x_1$:
<br>
$4x_1=1-3x_2-2x_3$
<br>
$\frac{4x_1}{4}=\frac{1-3x_2-2x_3}{4}$
<br>
$x_1=\frac{1}{4}-\frac{3x_2}{4}-\frac{1x_3}{2}$

In [17]:
import sympy as sp

x1, x2, x3 = sp.symbols('x1 x2 x3')
equation = sp.Eq(4*x1 + 3*x2 + 2*x3, 1)
solution = sp.solve(equation, x1)

for sol in solution:
    print("x1 =", sol)

x1 = -3*x2/4 - x3/2 + 1/4


- $3x-6y=0$
<br><br>
Solving for $x$:
<br>
$3x=0+6y$
<br>
$\frac{3x}{3}=\frac{6y}{3}$
<br>
$x=2y$

In [15]:
import sympy as sp

x, y = sp.symbols('x y')
equation = sp.Eq(3 * x - 6 * y, 0)
solution = sp.solve(equation, x)

for sol in solution:
    print("x =", sol)

x = 2*y


3. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x-y=0 \end{equation}
\begin{equation}
2x+y = 3 \end{equation}

Forward Elimination solving for $x$: <br>
$3x = 3$ <br>
$\frac{3x}{3} = \frac{3}{3}$ <br>
$x = 1$

Back Substitution solving for $y$: <br>
$x - y= 0$ <br>
$1 - y= 0$ <br>
$-y= -1$ <br>
$\frac{-y}{-1} = \frac{-1}{-1}$ <br>
$y = 1$

In [29]:
import numpy as np

# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

# Code for automating backward substitution
def backward_substitution(U):
    n = U.shape[0]
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        x[i] = U[i][-1] / U[i][i]
        for j in range(i - 1, -1, -1):
            U[j][-1] -= U[j][i] * x[i]
    
    return x

A = np.array([[1, -1, 0], [2, 1, 3]])

A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1,'\n')
A2 = RowScale(A1,1,1/3)
print("A2")
print(A2,'\n')
A3 = RowAdd(A2,1,0,1)
print("A3")
print(A3,'\n')


# Backward Substitution
solution = backward_substitution(A3)
print("Solution:")
print("x =", int(solution[0]))
print("y =", int(solution[1]))

A1
[[ 1. -1.  0.]
 [ 0.  3.  3.]] 

A2
[[ 1. -1.  0.]
 [ 0.  1.  1.]] 

A3
[[1. 0. 1.]
 [0. 1. 1.]] 

Solution:
x = 1
y = 1


b. <br>
\begin{equation}
x+5y= -1 \end{equation}
\begin{equation}
-x+y = -5 \end{equation}
\begin{equation}
2x+4y = 4 \end{equation}

$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    -1 & 1 &\bigm| & -5 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\frac{1}{6}\text{R}_{2}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{3}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    1 & 2 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & -3 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 3\text{R}_{2}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 5\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 4 \\
    0 & 1 &\bigm| & -1 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$
<br>

Backward Substitution:<br>
$x = 4$<br>
$y = -1$

In [34]:
import numpy as np

# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

A=np.array([[1,5,-1],[-1,1,-5],[2,4,4]])

A1 = RowAdd(A,0,1,1)
print("A1")
print(A1,'\n')
A2 = RowScale(A1,1,1/6)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,2,1/2)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,0,2,-1)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,1,2,3)
print("A5")
print(A5,'\n')
A6 = RowAdd(A5,1,0,-5)
print("A6")
print(A6,'\n')

print("Solution:")
print("x =", int(A6[0][2]))
print("y =", int(A6[1][2]))

A1
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 2.  4.  4.]] 

A2
[[ 1.  5. -1.]
 [ 0.  1. -1.]
 [ 2.  4.  4.]] 

A3
[[ 1.  5. -1.]
 [ 0.  1. -1.]
 [ 1.  2.  2.]] 

A4
[[ 1.  5. -1.]
 [ 0.  1. -1.]
 [ 0. -3.  3.]] 

A5
[[ 1.  5. -1.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]] 

A6
[[ 1.  0.  4.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]] 

Solution:
x = 4
y = -1


c. <br>
\begin{equation}
2x_1+3x_2-x_3= -1 \end{equation}
\begin{equation}
x_1+x_3 = 0 \end{equation}
\begin{equation}
-x_1+2x_2-2x_3 = 0 \end{equation}
<br>
$
\begin{pmatrix}
    2 & 3 & -1&\bigm| & -1 \\
    1 & 0 & 1&\bigm| & 0 \\
    -1 & 2 & -2&\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} ⇔ \text{R}_{3}}
\begin{pmatrix}
    2 & 3 & -1&\bigm| & -1 \\
    -1 & 2 & -2&\bigm| & 0 \\
    1 & 0 & 1&\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    2 & 3 & -1&\bigm| & -1 \\
    -3 & -1 & -1&\bigm| & 1 \\
    1 & 0 & 1&\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + 3\text{R}_{3}}
\begin{pmatrix}
    2 & 3 & -1&\bigm| & -1 \\
    0 & -1 & 2&\bigm| & 1 \\
    1 & 0 & 1&\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{3}}
\begin{pmatrix}
    1 & 3 & -2&\bigm| & -1 \\
    0 & -1 & 2&\bigm| & 1 \\
    1 & 0 & 1&\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & 3 & -2&\bigm| & -1 \\
    0 & -1 & 2&\bigm| & 1 \\
    0 & -3 & 3&\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\frac{1}{3}\text{R}_{3}}
\begin{pmatrix}
    1 & 3 & -2&\bigm| & -1 \\
    0 & -1 & 2&\bigm| & 1 \\
    0 & -1 & 1&\bigm| & \frac{1}{3} \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 3 & -2&\bigm| & -1 \\
    0 & -1 & 2&\bigm| & 1 \\
    0 & 0 & -1&\bigm| & -\frac{2}{3} \\
\end{pmatrix}
\xrightarrow{-1\text{R}_{3}}
\begin{pmatrix}
    1 & 3 & -2&\bigm| & -1 \\
    0 & -1 & 2&\bigm| & 1 \\
    0 & 0 & 1&\bigm| & \frac{2}{3} \\
\end{pmatrix}
\xrightarrow{-1\text{R}_{2}}
\begin{pmatrix}
    1 & 3 & -2&\bigm| & -1 \\
    0 & 1 & -2&\bigm| & -1 \\
    0 & 0 & 1&\bigm| & \frac{2}{3} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{pmatrix}
    1 & 2 & 0&\bigm| & 0 \\
    0 & 1 & -2&\bigm| & -1 \\
    0 & 0 & 1&\bigm| & \frac{2}{3} \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + 2\text{R}_{3}}
\begin{pmatrix}
    1 & 2 & 0&\bigm| & 0 \\
    0 & 1 & 0&\bigm| & \frac{1}{3} \\
    0 & 0 & 1&\bigm| & \frac{2}{3} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 2\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 0&\bigm| & -\frac{2}{3} \\
    0 & 1 & 0&\bigm| & \frac{1}{3} \\
    0 & 0 & 1&\bigm| & \frac{2}{3} \\
\end{pmatrix}
$
<br><br>

Backward Substitution:<br>
$x_1 = -\frac{2}{3}$<br>
$x_2 = \frac{1}{3}$<br>
$x_3 = \frac{2}{3}$


In [52]:
import numpy as np

# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

A=np.array([[2,3,-1,-1],[1,0,1,0],[-1,2,-2,0]])

A1 = RowSwap(A,1,2)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,1,-1)
print("A2")
print(A2,'\n')
A3 = RowAdd(A2,2,1,3)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,2,0,-1)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,0,2,-1)
print("A5")
print(A5,'\n')
A6 = RowScale(A5,2,1/3)
print("A6")
print(A6,'\n')
A7 = RowAdd(A6,1,2,-1)
print("A7")
print(A7,'\n')
A8 = RowScale(A7,1,-1)
print("A8")
print(A8,'\n')
A9 = RowScale(A8,2,-1)
print("A9")
print(A9,'\n')
A10 = RowAdd(A9,1,0,-1)
print("A10")
print(A10,'\n')
A11 = RowAdd(A10,2,1,2)
print("A11")
print(A11,'\n')
A12 = RowAdd(A11,1,0,-2)
print("A12")
print(A12,'\n')

print("Solution:")
print("x1 =", A12[0][3])
print("x2 =", A12[1][3])
print("x3 =", A12[2][3])

A1
[[ 2.  3. -1. -1.]
 [-1.  2. -2.  0.]
 [ 1.  0.  1.  0.]] 

A2
[[ 2.  3. -1. -1.]
 [-3. -1. -1.  1.]
 [ 1.  0.  1.  0.]] 

A3
[[ 2.  3. -1. -1.]
 [ 0. -1.  2.  1.]
 [ 1.  0.  1.  0.]] 

A4
[[ 1.  3. -2. -1.]
 [ 0. -1.  2.  1.]
 [ 1.  0.  1.  0.]] 

A5
[[ 1.  3. -2. -1.]
 [ 0. -1.  2.  1.]
 [ 0. -3.  3.  1.]] 

A6
[[ 1.          3.         -2.         -1.        ]
 [ 0.         -1.          2.          1.        ]
 [ 0.         -1.          1.          0.33333333]] 

A7
[[ 1.          3.         -2.         -1.        ]
 [ 0.         -1.          2.          1.        ]
 [ 0.          0.         -1.         -0.66666667]] 

A8
[[ 1.          3.         -2.         -1.        ]
 [-0.          1.         -2.         -1.        ]
 [ 0.          0.         -1.         -0.66666667]] 

A9
[[ 1.          3.         -2.         -1.        ]
 [-0.          1.         -2.         -1.        ]
 [-0.         -0.          1.          0.66666667]] 

A10
[[ 1.          2.          0.          0.    

4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or neither both.<br>
a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br><br>
It is neither. Although there are zeroes, it does not form a triangular shape in the lower left as it should for a row echelon. As you can see, the third row second column has a 1.

b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br><br>
It is a row echelon because it forms a triangular shape of zeroes in the lower left. It is not a reduced row echelon because of the presence of non-zero and non-one entries.

c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br><br>
It is neither because the supposed leading entry in the first row is a 0 when it should be a non-zero value to qualify as a row echelon. 

d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br><br>
It is neither. All entries in the matrix are zeroes. There are no non-zero leading entries present.

e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br><br>
It is neither. It does not form a triangular shape of zeroes in the lower left as it should for a row echelon. As you can see, the third row second column has a 1.

f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br><br>
It is neither because the supposed leading entry in the first row is a 0 when it should be a non-zero value. In the third row first column, it has an entry of 1, missing out in the triangular shape of zeroes in the lower left. Overall, it does not show any form of row echelon. 

g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br><br>
It is neither because the non-zero leading entries should somewhat form a diagonal to qualify as a row echelon. The issue here is the entry of 1 in the second row first column.

h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}
<br><br>
It is a row echelon because it forms a triangular shape of zeroes in the lower left without any issues regarding leading entries. It is not a reduced row echelon because there are non-zero and non-one entries present in the matrix. 

In [66]:
import numpy as np

def is_row_echelon(matrix):
    rows, cols = matrix.shape
    leading_col = -1

    if matrix[0][0] == 0:
        return False
    
    for i in range(rows):
        found_nonzero = False
        for j in range(cols):
            if matrix[i][j] != 0:
                found_nonzero = True
                if j <= leading_col:
                    return False  # Rule 3 violation
                leading_col = j
                break
        if not found_nonzero and i < rows - 1:
            return False  # Rule 1 violation

    return True

def is_reduced_row_echelon(matrix):
    if not is_row_echelon(matrix):
        return False

    rows, cols = matrix.shape

    for i in range(rows):
        found_nonzero = False
        for j in range(cols):
            if matrix[i][j] != 0:
                if matrix[i][j] != 1:
                    return False  # Leading entry is not 1
                found_nonzero = True
                break
        if not found_nonzero and i < rows - 1:
            return False  # Rule 1 violation

    return True

# Example matrices
matrices = [
    np.array([[1, 0, 1], [0, 0, 3], [0, 1, 0]]),
    np.array([[7, 0, 1, 0], [0, 1, -1, 4], [0, 0, 0, 0]]),
    np.array([[0, 1, 3, 0], [0, 0, 0, 1]]),
    np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]]),
    np.array([[1, 0, 3, -4, 0], [0, 0, 0, 0, 0], [0, 1, 5, 0, 1]]),
    np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]]),
    np.array([[1, 2, 3], [1, 0, 0], [0, 1, 1], [0, 0, 1]]),
    np.array([[2, 1, 3, 5], [0, 0, 1, -1], [0, 0, 0, 3], [0, 0, 0, 0]])
]

for i, matrix in enumerate(matrices):
    print(f"Matrix {chr(97+i)}:")
    if is_reduced_row_echelon(matrix):
        print("   Reduced Row Echelon Form")
    elif is_row_echelon(matrix):
        print("   Row Echelon Form")
    else:
        print("   Neither Row Echelon nor Reduced Row Echelon Form")
    print()


Matrix a:
   Neither Row Echelon nor Reduced Row Echelon Form

Matrix b:
   Row Echelon Form

Matrix c:
   Neither Row Echelon nor Reduced Row Echelon Form

Matrix d:
   Neither Row Echelon nor Reduced Row Echelon Form

Matrix e:
   Neither Row Echelon nor Reduced Row Echelon Form

Matrix f:
   Neither Row Echelon nor Reduced Row Echelon Form

Matrix g:
   Neither Row Echelon nor Reduced Row Echelon Form

Matrix h:
   Row Echelon Form



5. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x_1+2x_2-3x_3=9 \end{equation}
\begin{equation}
2x_1-x_2-x_3=0 \end{equation}
\begin{equation}
4x_1-x_2+x_3=4 \end{equation}

$
\begin{pmatrix}
    1 & 2 & -3&\bigm| & 9 \\
    2 & -1 & -1&\bigm| & 0 \\
    4 & -1 & 1&\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3&\bigm| & 9 \\
    2 & -1 & -1&\bigm| & 0 \\
    0 & 1 & 3&\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3&\bigm| & 9 \\
    0 & -5 & 5&\bigm| & -18 \\
    0 & 1 & 3&\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{5} \text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3&\bigm| & 9 \\
    0 & 1 & -1&\bigm| & \frac{18}{5} \\
    0 & 1 & 3&\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3&\bigm| & 9 \\
    0 & 1 & -1&\bigm| & \frac{18}{5} \\
    0 & 0 & 4&\bigm| & \frac{2}{5} \\
\end{pmatrix}
\xrightarrow{\frac{1}{4}\text{R}_{3}}
\begin{pmatrix}
    1 & 2 & -3&\bigm| & 9 \\
    0 & 1 & -1&\bigm| & \frac{18}{5} \\
    0 & 0 & 1&\bigm| & \frac{1}{10} \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{3}}
\begin{pmatrix}
    1 & 2 & -3&\bigm| & 9 \\
    0 & 1 & 0&\bigm| & \frac{37}{10} \\
    0 & 0 & 1&\bigm| & \frac{1}{10} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 2\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & -3&\bigm| & \frac{8}{5} \\
    0 & 1 & 0&\bigm| & \frac{37}{10} \\
    0 & 0 & 1&\bigm| & \frac{1}{10} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} + 3\text{R}_{3}}
\begin{pmatrix}
    1 & 0 & 0&\bigm| & \frac{19}{10} \\
    0 & 1 & 0&\bigm| & \frac{37}{10} \\
    0 & 0 & 1&\bigm| & \frac{1}{10} \\
\end{pmatrix}
$
<br><br>

Backward Substitution:<br>
$x_1 = \frac{19}{10}$<br>
$x_2 = \frac{37}{10}$<br>
$x_3 = \frac{1}{10}$

In [53]:
import numpy as np

# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

A=np.array([[1,2,-3,9],[2,-1,-1,0],[4,-1,1,4]])

A1 = RowAdd(A,1,2,-2)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,1,-2)
print("A2")
print(A2,'\n')
A3 = RowScale(A2,1,-1/5)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,2,-1)
print("A4")
print(A4,'\n')
A5 = RowScale(A4,2,1/4)
print("A5")
print(A5,'\n')
A6 = RowAdd(A5,2,1,1)
print("A6")
print(A6,'\n')
A7 = RowAdd(A6,1,0,-2)
print("A7")
print(A7,'\n')
A8 = RowAdd(A7,2,0,3)
print("A8")
print(A8,'\n')

print("Solution:")
print("x1 =", A8[0][3])
print("x2 =", A8[1][3])
print("x3 =", A8[2][3])

A1
[[ 1.  2. -3.  9.]
 [ 2. -1. -1.  0.]
 [ 0.  1.  3.  4.]] 

A2
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  0.   1.   3.   4.]] 

A3
[[ 1.   2.  -3.   9. ]
 [-0.   1.  -1.   3.6]
 [ 0.   1.   3.   4. ]] 

A4
[[ 1.   2.  -3.   9. ]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   4.   0.4]] 

A5
[[ 1.   2.  -3.   9. ]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   1.   0.1]] 

A6
[[ 1.   2.  -3.   9. ]
 [ 0.   1.   0.   3.7]
 [ 0.   0.   1.   0.1]] 

A7
[[ 1.   0.  -3.   1.6]
 [ 0.   1.   0.   3.7]
 [ 0.   0.   1.   0.1]] 

A8
[[1.  0.  0.  1.9]
 [0.  1.  0.  3.7]
 [0.  0.  1.  0.1]] 

Solution:
x1 = 1.8999999999999995
x2 = 3.7
x3 = 0.09999999999999998


b. <br>
\begin{equation}
x+2y= -1 \end{equation}
\begin{equation}
2x+y+z = 1 \end{equation}
\begin{equation}
-x+y-z = -1 \end{equation}

$
\begin{pmatrix}
    1 & 2 & 0&\bigm| & -1 \\
    2 & 1 & 1&\bigm| & 1 \\
    -1 & 1 & -1&\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{3}}
\begin{pmatrix}
    1 & 2 & 0&\bigm| & -1 \\
    1 & 2 & 0&\bigm| & 0 \\
    -1 & 1 & -1&\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0&\bigm| & -1 \\
    0 & 0 & 0&\bigm| & 1 \\
    -1 & 1 & -1&\bigm| & -1 \\
\end{pmatrix}
$
<br><br>

As $0 ≠ 1$, it is an inconsistent system of linear equation. 


In [57]:
import numpy as np

# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

A=np.array([[1,2,0,-1],[2,1,1,1],[-1,1,-1,-1]])

A1 = RowAdd(A,2,1,1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,1,-1)
print("A2")
print(A2,'\n')

A1
[[ 1.  2.  0. -1.]
 [ 1.  2.  0.  0.]
 [-1.  1. -1. -1.]] 

A2
[[ 1.  2.  0. -1.]
 [ 0.  0.  0.  1.]
 [-1.  1. -1. -1.]] 



c. <br>
\begin{equation}
x_1-3x_2-2x_3=0 \end{equation}
\begin{equation}
-x_1+2x_2+x_3=0 \end{equation}
\begin{equation}
2x_1+4x_2+6x_3=0 \end{equation}
<br>

$
\begin{pmatrix}
    1 & -3 & -2&\bigm| & 0 \\
    -1 & 2 & 1&\bigm| & 0 \\
    2 & 4 & 6&\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2&\bigm| & 0 \\
    0 & -1 & -1&\bigm| & 0 \\
    2 & 4 & 6&\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2&\bigm| & 0 \\
    0 & -1 & -1&\bigm| & 0 \\
    0 & 10 & 10&\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 10\text{R}_{2}}
\begin{pmatrix}
    1 & -3 & -2&\bigm| & 0 \\
    0 & -1 & -1&\bigm| & 0 \\
    0 & 0 & 0&\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 3\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1&\bigm| & 0 \\
    0 & -1 & -1&\bigm| & 0 \\
    0 & 0 & 0&\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{-1\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1&\bigm| & 0 \\
    0 & 1 & 1&\bigm| & 0 \\
    0 & 0 & 0&\bigm| & 0 \\
\end{pmatrix}
$
<br><br>

The constant term is zero. It is a homogenous system that have at least one solution.<br>

Finding $x_1$:<br>
$x_1 + x_3 = 0$<br>
$x_1 = -x_3$<br>

Finding $x_2$:<br>
$x_2 + x_3 = 0$<br>
$x_2 = -x_3$<br>

Finding $x_3$:<br>
$0x_1 + 0x_2 + 0x_3 = 0$<br>
$x_3$ can take any real value. 


In [59]:
import numpy as np

# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

A=np.array([[1,-3,-2,0],[-1,2,1,0],[2,4,6,0]])

A1 = RowAdd(A,0,1,1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,0,2,-2)
print("A2")
print(A2,'\n')
A3 = RowAdd(A2,1,2,10)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,1,0,-3)
print("A4")
print(A4,'\n')
A5 = RowScale(A4,1,-1)
print("A5")
print(A5,'\n')

print("Solution:")
print("x1 =", A5[0][3])
print("x2 =", A5[1][3])
print("x3 =", A5[2][3])

A1
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 2.  4.  6.  0.]] 

A2
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0. 10. 10.  0.]] 

A3
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0.  0.  0.  0.]] 

A4
[[ 1.  0.  1.  0.]
 [ 0. -1. -1.  0.]
 [ 0.  0.  0.  0.]] 

A5
[[ 1.  0.  1.  0.]
 [-0.  1.  1. -0.]
 [ 0.  0.  0.  0.]] 

Solution:
x1 = 0.0
x2 = -0.0
x3 = 0.0


d. <br>
\begin{equation}
w+x+2y+z=1 \end{equation}
\begin{equation}
w-x-y+z=0 \end{equation}
\begin{equation}
x+y=1 \end{equation}
\begin{equation}
w+x+z=2 \end{equation}
<br>

$
\begin{pmatrix}
    1 & 1 & 2& 1&\bigm| & 1 \\
    1 & -1 & -1& 1&\bigm| & 0 \\
    0 & 1 & 1& 0&\bigm| & 1 \\
    1 & 1 & 0& 1&\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 & 2& 1&\bigm| & 1 \\
    0 & -2 & -3& 0&\bigm| & -1 \\
    0 & 1 & 1& 0&\bigm| & 1 \\
    1 & 1 & 0& 1&\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + 3\text{R}_{3}}
\begin{pmatrix}
    1 & 1 & 2& 1&\bigm| & 1 \\
    0 & 1 & 0& 0&\bigm| & 2 \\
    0 & 1 & 1& 0&\bigm| & 1 \\
    1 & 1 & 0& 1&\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 1 & 2& 1&\bigm| & 1 \\
    0 & 1 & 0& 0&\bigm| & 2 \\
    0 & 0 & 1& 0&\bigm| & -1 \\
    1 & 1 & 0& 1&\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 & 2& 1&\bigm| & 1 \\
    0 & 1 & 0& 0&\bigm| & 2 \\
    0 & 0 & 1& 0&\bigm| & -1 \\
    0 & 0 & -2& 0&\bigm| & 1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{4} + 2\text{R}_{3}}
\begin{pmatrix}
    1 & 1 & 2& 1&\bigm| & 1 \\
    0 & 1 & 0& 0&\bigm| & 2 \\
    0 & 0 & 1& 0&\bigm| & -1 \\
    0 & 0 & 0& 0&\bigm| & -1 \\
\end{pmatrix}
$
<br><br>

As $0 ≠ -1$, it is an inconsistent system of linear equation. 

In [61]:
import numpy as np

# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

A=np.array([[1,1,2,1,1],[1,-1,-1,1,0],[0,1,1,0,1],[1,1,0,1,2]])

A1 = RowAdd(A,0,1,-1)
print("A1")
print(A1,'\n')
A2 = RowAdd(A1,2,1,3)
print("A2")
print(A2,'\n')
A3 = RowAdd(A2,1,2,-1)
print("A3")
print(A3,'\n')
A4 = RowAdd(A3,0,3,-1)
print("A4")
print(A4,'\n')
A5 = RowAdd(A4,2,3,2)
print("A5")
print(A5,'\n')

A1
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0.  1.  1.  0.  1.]
 [ 1.  1.  0.  1.  2.]] 

A2
[[1. 1. 2. 1. 1.]
 [0. 1. 0. 0. 2.]
 [0. 1. 1. 0. 1.]
 [1. 1. 0. 1. 2.]] 

A3
[[ 1.  1.  2.  1.  1.]
 [ 0.  1.  0.  0.  2.]
 [ 0.  0.  1.  0. -1.]
 [ 1.  1.  0.  1.  2.]] 

A4
[[ 1.  1.  2.  1.  1.]
 [ 0.  1.  0.  0.  2.]
 [ 0.  0.  1.  0. -1.]
 [ 0.  0. -2.  0.  1.]] 

A5
[[ 1.  1.  2.  1.  1.]
 [ 0.  1.  0.  0.  2.]
 [ 0.  0.  1.  0. -1.]
 [ 0.  0.  0.  0. -1.]] 



6. Determine if the vectors are linear combinations<br>
a. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} -1 \\ 3 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\
\end{equation}
<br>

\begin{equation}
    \begin{bmatrix} -1 \\ 3 \end{bmatrix}\ x + \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\ y = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
\end{equation}

<br><br>
$-x + 2y = 1$<br>
$3x - 6y = 2$ <br><br>
$
\begin{pmatrix}
    -1 & 2 &\bigm| & 1 \\
    3 & -6 &\bigm| & 2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + 3\text{R}_{1}}
\begin{pmatrix}
    -1 & 2 &\bigm| & 1 \\
    0 & 0 &\bigm| & 5 \\
\end{pmatrix}
$<br><br>

As $0 ≠ 5$, it is an inconsistent system of linear equation. Therefore, it is not a linear combination.


b. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br>

\begin{equation}
    \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\ x + \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\ y = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
\end{equation}

<br><br>
$x = 1$<br>
$x + y = 2$<br>
$y = 3$ <br><br>
$
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    1 & 1 &\bigm| & 2 \\
    0 & 1 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 1 &\bigm| & 3 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 1 \\
    0 & 1 &\bigm| & 1 \\
    0 & 0 &\bigm| & 2 \\
\end{pmatrix}
$<br><br>

As $0 ≠ 2$, it is an inconsistent system of linear equation. Therefore, it is not a linear combination.

c. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br>

\begin{equation}
    \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\ x + \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\ y = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
\end{equation}

<br><br>
$x = 3$<br>
$x + y = 1$<br>
$y = -2$ <br><br>
$
\begin{pmatrix}
    1 & 0 &\bigm| & 3 \\
    1 & 1 &\bigm| & 1 \\
    0 & 1 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 0 &\bigm| & 3 \\
    0 & 1 &\bigm| & -2 \\
    0 & 1 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 3 \\
    0 & 1 &\bigm| & -2 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$<br><br>

\begin{equation}
    \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\ 3 + \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\ -2 = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
\end{equation}

It is a linear combination.

7. Show that the following vectors are a span: <br>
a.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 1 \\ \end{bmatrix}
\begin{bmatrix}1 \\ -1 \\ \end{bmatrix}
\end{pmatrix}
$
<br>

$
\begin{bmatrix}1 \\ 1 \\ \end{bmatrix} x + \begin{bmatrix}1 \\ -1 \\ \end{bmatrix} y = \begin{bmatrix}a \\ b \\ \end{bmatrix}
$<br><br>

$x + y = a$<br>
$x - y = b$<br><br>

$
\begin{pmatrix}
    1 & 1 &\bigm| & a \\
    1 & -1 &\bigm| & b \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 &\bigm| & a \\
    0 & -2 &\bigm| & b-a \\
\end{pmatrix}
\xrightarrow{-\frac{1}{2} \text{R}_{2}}
\begin{pmatrix}
    1 & 1 &\bigm| & a \\
    0 & 1 &\bigm| & -\frac{b-a}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & \frac{b+a}{2}\\
    0 & 1 &\bigm| & -\frac{b-a}{2} \\
\end{pmatrix}
$<br><br>

It is a span.

b.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br>
c.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>

$
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix} x + \begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix} y + \begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix} = \begin{bmatrix}a \\ b \\ c\end{bmatrix}
$<br>

$x + y = a$<br>
$y + z = b$<br>
$x + z = c$<br><br>

$
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    1 & 0 & 1 &\bigm| & c \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    0 & -1 & 1 &\bigm| & c-a \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 2 &\bigm| & c-a+b \\
\end{pmatrix}
\xrightarrow{\frac{1}{2} \text{R}_{3}}
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 1 &\bigm| & b \\
    0 & 0 & 1 &\bigm| & \frac{c-a+b}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{3}}
\begin{pmatrix}
    1 & 1 & 0 &\bigm| & a \\
    0 & 1 & 0 &\bigm| & b - \frac{c-a+b}{2}\\
    0 & 0 & 1 &\bigm| & \frac{c-a+b}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & a - b - \frac{c-a+b}{2} \\
    0 & 1 & 0 &\bigm| & b - \frac{c-a+b}{2}\\
    0 & 0 & 1 &\bigm| & \frac{c-a+b}{2} \\
\end{pmatrix}
$<br>

It is a span.

8. Show that the following vectors are linearly independent:<br>
a. <br>
\begin{equation}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{equation}
<br>
$n$ = 4 (rows) and $m$ = 4 (columns) means that $m$ is not greater than $n$. As it does not follow condition 4 of linear dependence (m > n), it is $\textbf{linearly independent}.$<br><br>

b. <br>
    \begin{equation}
    \begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
    \begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
    \begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
    \begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
    \end{equation}
    <br>
    $n$ = 4 (rows) and $m$ = 4 (columns) means that $m$ is not greater than $n$. As it does not follow condition 4 of linear dependence (m > n), it is $\textbf{linearly independent}.$<br><br>
    
c. <br>
    \begin{equation}
    \begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
    \begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
    \begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
    \begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
    \end{equation}
    $n$ = 4 (rows) and $m$ = 4 (columns) means that $m$ is not greater than $n$. As it does not follow condition 4 of linear dependence (m > n), it is $\textbf{linearly independent}.$